export default [
  {
    title: '管理中心',
    href: '/console',
    leaf: false,
    icon: 'fa-caret-down'
  }, {
    title: '管理首页',
    href: '/console/home',
    leaf: true,
    icon: 'fa-dashboard'
  }, {
    title: '详情明细',
    href: '/console/details',
    leaf: true,
    icon: 'fa-list'
  }, {
    title: '渠道管理',
    href: '/proxy',
    leaf: false,
    icon: 'fa-caret-down'
  }, {
    title: '代理商管理',
    href: '/proxy/agents',
    leaf: true,
    icon: 'fa-user-secret'
  }, {
    title: '分润设置',
    href: '/proxy/profits',
    leaf: true,
    icon: 'fa-money'
  }, {
    title: '二级代理商管理',
    href: '/proxy/secAgents',
    leaf: true,
    icon: 'fa-user'
  }, {
    title: '二级分润设置',
    href: '/proxy/secProfits',
    leaf: true,
    icon: 'fa-rmb'
  }, {
    title: '网吧部署',
    href: '/netbar',
    leaf: false,
    icon: 'fa-caret-down'
  }, {
    title: '网吧资料',
    href: '/netbar/info',
    leaf: true,
    icon: 'fa-desktop'
  }, {
    title: '应用部署',
    href: '/netbar/deploy',
    leaf: true,
    icon: 'fa-cloud-upload'
  }, {
    title: '系统设置',
    href: '/settings',
    leaf: false,
    icon: 'fa-caret-down'
  }, {
    title: '角色设置',
    href: '/settings/role',
    leaf: true,
    icon: 'fa-users'
  }, {
    title: '用户管理',
    href: '/settings/user',
    leaf: true,
    icon: 'fa-user-circle'
  }, {
    title: '网吧权限',
    href: '/settings/authority',
    leaf: true,
    icon: 'fa-grav'
  }, {
    title: '门店管理',
    href: '/store',
    leaf: false,
    icon: 'fa-caret-down'
  }, {
    title: '交易账单',
    href: '/store/bill',
    leaf: true,
    icon: 'fa-file-text-o'
  }
]
